private ['_side','_tiMode','_u'];

_side = _this;

_u=      ['rhs_msv_driver_armored'];
_u pushBack  'rhs_msv_efreitor';
_u pushBack  'rhs_msv_driver';
_u pushBack  'rhs_msv_engineer';
_u pushBack  'rhs_msv_crew_commander';
_u pushBack  'rhs_msv_grenadier_rpg';
_u pushBack  'rhs_msv_strelok_rpg_assist';
_u pushBack  'rhs_msv_combatcrew';
_u pushBack  'rhs_msv_junior_sergeant';
_u pushBack  'rhs_msv_machinegunner';
_u pushBack  'rhs_msv_armoredcrew';
_u pushBack  'rhs_msv_machinegunner_assistant';
_u pushBack  'rhs_msv_crew';
_u pushBack  'rhs_msv_marksman';
_u pushBack  'rhs_msv_medic';
_u pushBack  'rhs_msv_arifleman';
_u pushBack  'rhs_msv_officer';
_u pushBack  'rhs_msv_at';
_u pushBack  'rhs_msv_sergeant';
_u pushBack  'rhs_msv_aa';
_u pushBack  'rhs_msv_officer_armored';
_u pushBack  'rhs_msv_RShG2';
_u pushBack  'rhs_msv_grenadier';
_u pushBack  'rhs_msv_LAT';
_u pushBack  'rhs_msv_rifleman';

_u pushBack  'rhs_mvd_izlom_grenadier_rpg';
_u pushBack  'rhs_mvd_izlom_efreitor';
_u pushBack  'rhs_mvd_izlom_arifleman';
_u pushBack  'rhs_mvd_izlom_marksman';
_u pushBack  'rhs_mvd_izlom_marksman_vss';
_u pushBack  'rhs_mvd_izlom_rifleman';
_u pushBack  'rhs_mvd_izlom_rifleman_asval';
_u pushBack  'rhs_mvd_izlom_rifleman_LAT';
_u pushBack  'rhs_mvd_izlom_machinegunner';

_u pushBack  'rhs_vdv_recon_sergeant';
_u pushBack  'rhs_vdv_recon_efreitor';
_u pushBack  'rhs_vdv_recon_arifleman';
_u pushBack  'rhs_vdv_recon_medic';
_u pushBack  'rhs_vdv_recon_rifleman_scout';
_u pushBack  'rhs_vdv_recon_grenadier_scout';
_u pushBack  'rhs_vdv_recon_arifleman_scout';
_u pushBack  'rhs_vdv_recon_marksman';
_u pushBack  'rhs_vdv_recon_marksman_vss';
_u pushBack  'rhs_vdv_recon_rifleman_akms';
_u pushBack  'rhs_vdv_recon_rifleman_ak103';
_u pushBack  'rhs_vdv_recon_rifleman_asval';
_u pushBack  'rhs_vdv_recon_grenadier';
_u pushBack  'rhs_vdv_recon_rifleman_lat';
_u pushBack  'rhs_vdv_recon_rifleman_l';
_u pushBack  'rhs_vdv_at';


_u pushBack  'rhs_vmf_recon_grenadier_scout';
_u pushBack  'rhs_vmf_recon_arifleman_scout';
_u pushBack  'rhs_vmf_recon_rifleman_akms';
_u pushBack  'rhs_vmf_recon_rifleman';
_u pushBack  'rhs_vmf_recon_marksman_vss';
_u pushBack  'rhs_vmf_recon_officer_armored';
_u pushBack  'rhs_vmf_recon_rifleman_scout';
_u pushBack  'rhs_vmf_recon_medic';
_u pushBack  'rhs_vmf_recon_rifleman_l';
_u pushBack  'rhs_vmf_recon_grenadier';
_u pushBack  'rhs_vmf_recon_marksman';
_u pushBack  'rhs_vmf_recon_officer';
_u pushBack  'rhs_vmf_recon_rifleman_asval';
_u pushBack  'rhs_vmf_recon_sergeant';
_u pushBack  'rhs_vmf_recon_rifleman_scout_akm';
_u pushBack  'rhs_vmf_recon_machinegunner_assistant';
_u pushBack  'rhs_vmf_recon_rifleman_lat';
_u pushBack  'rhs_vmf_recon_arifleman';
_u pushBack  'rhs_vmf_recon_efreitor';

_u pushBack  'FGN_RuOSN_Sapper_P_Berezhka';
_u pushBack  'FGN_RuOSN_JSergeant_Berezhka';
_u pushBack  'FGN_RuOSN_MarksmanVSS_Berezhka';
_u pushBack  'FGN_RuOSN_MGunner_P_Berezhka';
_u pushBack  'FGN_RuOSN_RiflemanGP25_P_Berezhka';
_u pushBack  'FGN_RuOSN_Efreitor_Berezhka';
_u pushBack  'FGN_RuOSN_RiflemanAT_Berezhka';
_u pushBack  'FGN_RuOSN_MarksmanSVD_Berezhka';
_u pushBack  'FGN_RuOSN_Sergeant_P_Berezhka';
_u pushBack  'FGN_RuOSN_RiflemanASVal_Berezhka';
_u pushBack  'FGN_RuOSN_RiflemanAP_Berezhka';
_u pushBack  'FGN_RuOSN_Medic_Berezhka';
_u pushBack  'FGN_RuVDVRecon_RiflemanGP25';
_u pushBack  'FGN_RuVDVRecon_RiflemanAKMS';
_u pushBack  'FGN_RuVDVRecon_Marksman';
_u pushBack  'FGN_RuVDVRecon_Sapper';
_u pushBack  'FGN_RuVDVRecon_JSergeant';
_u pushBack  'FGN_RuVDVRecon_Efreitor';

_u pushBack  'rhs_vdv_flora_at';

_u pushBack  'rhs_pilot_tan';
_u pushBack  'rhs_pilot_transport_heli';
_u pushBack  'rhs_pilot';
_u pushBack  'rhs_pilot_combat_heli';

missionNamespace setVariable [Format ["WF_%1BARRACKSUNITS", _side], _u];
if (local player) then {['BARRACKS', _side, _u] Call WFCL_fnc_initFaction};

_u =      ['rhs_btr60_msv'];
_u  pushBack  'rhs_btr70_msv';
_u  pushBack  'rhs_btr80_msv';
_u  pushBack  'rhs_btr80a_msv';
_u  pushBack  'rhs_tigr_msv';
_u  pushBack  'rhs_tigr_3camo_msv';
_u  pushBack  'rhs_tigr_sts_msv';
_u  pushBack  'rhs_tigr_sts_3camo_msv';
_u  pushBack  'rhs_tigr_m_msv';
_u  pushBack  'rhs_tigr_m_3camo_msv';
_u  pushBack  'CUP_O_UAZ_METIS_RU';
_u  pushBack  'RHS_UAZ_MSV_01';
_u  pushBack  'rhs_uaz_open_MSV_01';
_u  pushBack  'rhsgref_BRDM2_msv';
_u  pushBack  'rhsgref_BRDM2_ATGM_msv';
//_u  pushBack  'RHS_BM21_MSV_01';
_u  pushBack  'CUP_O_BM21_RU';
_u  pushBack  'CUP_O_LR_Ambulance_TKA';
_u  pushBack  'CUP_O_GAZ_Vodnik_PK_RU';
_u  pushBack  'CUP_O_GAZ_Vodnik_AGS_RU';
_u  pushBack  'CUP_O_GAZ_Vodnik_BPPU_RU';
_u  pushBack  'CUP_O_BTR90_RU';
_u  pushBack  'rhs_gaz66_msv';
_u  pushBack  'rhs_gaz66_ammo_msv';
_u  pushBack  'rhs_gaz66_flat_msv';
_u  pushBack  'rhs_gaz66o_msv';
_u  pushBack  'rhs_gaz66o_flat_msv';
_u  pushBack  'rhs_gaz66_zu23_msv';
_u  pushBack  'rhs_gaz66_repair_msv';
_u  pushBack  'rhs_zil131_vdv';
_u  pushBack  'rhs_kamaz5350_msv';
_u  pushBack  'rhs_kamaz5350_flatbed_cover_msv';
_u  pushBack  'rhs_kamaz5350_open_msv';
_u  pushBack  'rhs_kamaz5350_flatbed_msv';
_u  pushBack  'RHS_Ural_MSV_01';
_u  pushBack  'RHS_Ural_Fuel_MSV_01';
_u  pushBack  'RHS_Ural_Repair_MSV_01';
//_u  pushBack  'RHS_Ural_Open_MSV_01';
_u  pushBack  'RHS_Ural_Zu23_MSV_01';
_u  pushBack  'rhsgref_cdf_reg_uaz_ags';
_u  pushBack  'rhsgref_cdf_reg_uaz_dshkm';
_u  pushBack  'rhsgref_cdf_reg_uaz_spg9';
_u  pushBack  'rhs_typhoon_vdv';
_u  pushBack 'CUP_C_TT650_RU';
_u  pushBack 'dbo_CIV_new_bike';

missionNamespace setVariable [Format ["WF_%1LIGHTUNITS", _side], _u];
if (local player) then {['LIGHT', _side, _u] Call WFCL_fnc_initFaction};

_u =      ['rhs_bmp2k_msv'];
_u  pushBack  'rhs_bmp2d_msv';
_u  pushBack  'rhs_bmp3m_msv';
_u  pushBack  'rhs_bmp3mera_msv';
_u  pushBack  'rhs_t72bd_tv';
_u  pushBack  'rhs_t72be_tv';
_u  pushBack  'rhs_t80a';
_u  pushBack  'rhs_t80ue1';
_u  pushBack  'rhs_t90a_tv';
_u  pushBack  'rhs_t90sab_tv';
_u  pushBack  'rhs_t90sm_tv';
_u  pushBack  'rhs_sprut_vdv';
_u  pushBack  'rhs_bmd1pk';
_u  pushBack  'rhs_bmd1r';
_u  pushBack  'rhs_bmd2k';
_u  pushBack  'rhs_bmd2m';
_u  pushBack  'rhs_bmd4ma_vdv';
_u  pushBack  'rhs_zsu234_aa';
_u  pushBack  'rhs_2s3_tv';
_u  pushBack  'rhs_2s1_tv';
_u pushBack 'CUP_O_2S6M_RU';
_u pushBack 'I_Truck_02_MRL_F_OPFOR';

missionNamespace setVariable [Format ["WF_%1HEAVYUNITS", _side], _u];
if (local player) then {['HEAVY', _side, _u] Call WFCL_fnc_initFaction};


_u =      ['RHS_Mi8AMT_vvsc'];
_u  pushBack 'rhsgref_mi24g_CAS';
_u  pushBack  'RHS_Mi8AMTSh_vvsc';
_u  pushBack  'RHS_Mi8MTV3_heavy_vvsc';
_u  pushBack  'CUP_O_MI6T_RU';
_u pushBack 'CUP_O_Mi8_medevac_RU';
_u  pushBack  'RHS_Ka52_vvsc';
_u  pushBack  'rhs_ka60_c';
_u  pushBack  'CUP_O_KA60_GREY_RU';
_u  pushBack  'rhs_mi28n_vvsc';
_u  pushBack  'RHS_TU95MS_vvs_old';
_u  pushBack 'CUP_O_Su25_Dyn_RU';
_u  pushBack 'rhs_mig29sm_vvsc';
_u pushBack 'CUP_O_AN2_TK';
_u  pushBack 'CUP_O_C47_SLA';
_u pushBack 'CUP_O_L39_TK';
_u pushBack 'I_Plane_Fighter_03_dynamicLoadout_F';
_u pushBack 'CUP_O_SU34_RU';
_u pushBack 'JS_JC_SU35';
//_u  pushBack  'RHS_T50_vvs_generic_ext';

missionNamespace setVariable [Format ["WF_%1AIRCRAFTUNITS", _side], _u];
if (local player) then {['AIRCRAFT', _side, _u] Call WFCL_fnc_initFaction};

_u = [];

_u  pushBack 'CUP_O_Su25_Dyn_RU';
_u  pushBack 'rhs_mig29sm_vvsc';
_u pushBack 'CUP_O_AN2_TK';
_u  pushBack 'CUP_O_C47_SLA';
_u pushBack 'CUP_O_L39_TK';
_u pushBack 'I_Plane_Fighter_03_dynamicLoadout_F';
_u pushBack 'CUP_O_SU34_RU';
_u pushBack 'JS_JC_SU35';
//_u  pushBack  'RHS_T50_vvs_generic_ext';

missionNamespace setVariable [Format ["WF_%1AIRPORTUNITS", _side], _u];
if (local player) then {['AIRPORT', _side, _u] Call WFCL_fnc_initFaction};

_u 			= ["C_Quadbike_01_F"];
_u pushBack "dbo_CIV_ol_bike";
_u pushBack "CUP_C_TT650_TK_CIV";
_u pushBack "CUP_C_Octavia_CIV";
_u pushBack "CUP_C_Golf4_yellow_Civ";
_u pushBack "CUP_C_Golf4_black_Civ";
_u pushBack 'CUP_C_SUV_TK';
_u pushBack 'CUP_O_PBX_RU';
_u pushBack "CUP_C_Ural_Civ_01";
_u pushBack "CUP_C_Ural_Civ_02";
_u pushBack "CUP_C_Ural_Open_Civ_01";
_u pushBack "C_Truck_02_fuel_F";
if ((missionNamespace getVariable "WF_C_UNITS_TOWN_PURCHASE") > 0) then {
	_u pushBack (missionNamespace getVariable "WF_EASTSOLDIER");
	_u pushBack 'rhs_msv_medic';
	_u pushBack 'rhs_msv_engineer';
	_u pushBack 'rhs_msv_LAT';
	_u pushBack 'rhs_msv_machinegunner';
	_u pushBack 'rhs_msv_aa';
};

missionNamespace setVariable [Format ["WF_%1DEPOTUNITS", _side], _u];
if (local player) then {['DEPOT', _side, _u] Call WFCL_fnc_initFaction};
