Private ['_side','_u'];

_side = _this;

_u=      ['rhsusf_army_ocp_arb_engineer'];
_u pushBack 'rhsusf_army_ocp_arb_grenadier';
_u pushBack 'rhsusf_army_ocp_arb_medic';
_u pushBack 'rhsusf_army_ocp_rifleman_arb_m16';
_u pushBack 'rhsusf_army_ocp_arb_machinegunner';
_u pushBack 'rhsusf_army_ocp_arb_sniper_m107';
_u pushBack 'rhsusf_army_ocp_arb_rifleman_m590';
_u pushBack 'rhsusf_army_ocp_arb_riflemanat';
_u pushBack 'rhsusf_army_ocp_arb_squadleader';
_u pushBack 'rhsusf_army_ocp_arb_autoriflemana';
_u pushBack 'rhsusf_army_ocp_arb_teamleader';
_u pushBack 'rhsusf_army_ocp_arb_marksman';
_u pushBack 'rhsusf_army_ocp_arb_machinegunnera';
_u pushBack 'rhsusf_army_ocp_arb_rifleman';
_u pushBack 'rhsusf_army_ocp_arb_autorifleman';
_u pushBack 'rhsusf_army_ocp_arb_riflemanl';


_u pushBack 'rhsusf_army_ocp_rifleman_m16';
_u pushBack 'rhsusf_army_ocp_sniper';
_u pushBack 'rhsusf_army_ocp_rifleman_m4';
_u pushBack 'rhsusf_army_ocp_engineer';
_u pushBack 'rhsusf_army_ocp_autorifleman';
_u pushBack 'rhsusf_army_ocp_fso';
_u pushBack 'rhsusf_army_ocp_driver_armored';
_u pushBack 'rhsusf_army_ocp_rifleman';
_u pushBack 'rhsusf_army_ocp_sniper_m24sws';
_u pushBack 'rhsusf_army_ocp_riflemanl';
_u pushBack 'rhsusf_army_ocp_maaws';
_u pushBack 'rhsusf_army_ocp_javelin';
_u pushBack 'rhsusf_army_ocp_javelin_assistant';
_u pushBack 'rhsusf_army_ocp_riflemanat';
_u pushBack 'rhsusf_army_ocp_machinegunnera';
_u pushBack 'rhsusf_army_ocp_explosives';
_u pushBack 'rhsusf_army_ocp_medic';
_u pushBack 'rhsusf_army_ocp_autoriflemana';
_u pushBack 'rhsusf_army_ocp_aa';
_u pushBack 'rhsusf_army_ocp_combatcrewman';
_u pushBack 'rhsusf_army_ocp_rifleman_m590';
_u pushBack 'rhsusf_army_ocp_squadleader';
_u pushBack 'rhsusf_army_ocp_crewman';
_u pushBack 'rhsusf_army_ocp_machinegunner';
_u pushBack 'rhsusf_army_ocp_sniper_m107';
_u pushBack 'rhsusf_army_ocp_officer';
_u pushBack 'rhsusf_army_ocp_driver';
_u pushBack 'rhsusf_army_ocp_grenadier';
_u pushBack 'rhsusf_army_ocp_teamleader';
_u pushBack 'rhsusf_army_ocp_marksman';
_u pushBack 'rhsusf_army_ocp_helipilot';
_u pushBack 'rhsusf_army_ocp_jfo';
_u pushBack 'rhsusf_army_ocp_helicrew';

_u pushBack 'rhsusf_navy_marpat_wd_medic';
_u pushBack 'rhsusf_navy_sarc_w';
_u pushBack 'rhsusf_navy_sarc_w_fast';

_u pushBack 'rhsusf_airforce_jetpilot';
_u pushBack 'rhsusf_airforce_pilot';

_u pushBack 'rhsusf_socom_marsoc_sniper_m107';
_u pushBack 'rhsusf_socom_marsoc_jtac';
_u pushBack 'rhsusf_socom_marsoc_sniper';
_u pushBack 'rhsusf_socom_marsoc_cso_cqb';
_u pushBack 'rhsusf_socom_marsoc_elementleader';
_u pushBack 'rhsusf_socom_marsoc_spotter';
_u pushBack 'rhsusf_socom_marsoc_cso_mechanic';
_u pushBack 'rhsusf_socom_marsoc_cso_light';
_u pushBack 'rhsusf_socom_swcc_officer';
_u pushBack 'rhsusf_socom_marsoc_sarc';
_u pushBack 'rhsusf_socom_marsoc_cso_breacher';
_u pushBack 'rhsusf_socom_marsoc_cso';
_u pushBack 'rhsusf_socom_marsoc_cso_grenadier';
_u pushBack 'rhsusf_socom_marsoc_cso_eod';
_u pushBack 'rhsusf_socom_marsoc_teamleader';
_u pushBack 'rhsusf_socom_marsoc_teamchief';
_u pushBack 'rhsusf_socom_swcc_crewman';
_u pushBack 'rhsusf_socom_marsoc_jfo';

_u pushBack 'rhsusf_usmc_marpat_wd_helicrew';
_u pushBack 'rhsusf_usmc_marpat_wd_helipilot';
_u pushBack 'rhsusf_usmc_marpat_wd_gunner';
_u pushBack 'rhsusf_usmc_marpat_wd_grenadier_m32';
_u pushBack 'rhsusf_usmc_marpat_wd_sniper';
_u pushBack 'rhsusf_usmc_marpat_wd_rifleman_m590';
_u pushBack 'rhsusf_usmc_marpat_wd_spotter';
_u pushBack 'rhsusf_usmc_marpat_wd_grenadier';
_u pushBack 'rhsusf_usmc_marpat_wd_autorifleman_m249_ass';
_u pushBack 'rhsusf_usmc_marpat_wd_sniper_m110';
_u pushBack 'rhsusf_usmc_marpat_wd_autorifleman_m249';
_u pushBack 'rhsusf_usmc_marpat_wd_javelin_assistant';
_u pushBack 'rhsusf_usmc_marpat_wd_driver';
_u pushBack 'rhsusf_usmc_marpat_wd_sniper_m107';
_u pushBack 'rhsusf_usmc_marpat_wd_autorifleman';
_u pushBack 'rhsusf_usmc_marpat_wd_rifleman_law';
_u pushBack 'rhsusf_usmc_marpat_wd_machinegunner';
_u pushBack 'rhsusf_usmc_marpat_wd_stinger';
_u pushBack 'rhsusf_usmc_marpat_wd_officer';
_u pushBack 'rhsusf_usmc_marpat_wd_rifleman_light';
_u pushBack 'rhsusf_usmc_marpat_wd_crewman';
_u pushBack 'rhsusf_usmc_marpat_wd_javelin';
_u pushBack 'rhsusf_usmc_marpat_wd_combatcrewman';
_u pushBack 'rhsusf_usmc_marpat_wd_rifleman';
_u pushBack 'rhsusf_usmc_marpat_wd_fso';
_u pushBack 'rhsusf_usmc_marpat_wd_teamleader';
_u pushBack 'rhsusf_usmc_marpat_wd_engineer';
_u pushBack 'rhsusf_usmc_marpat_wd_marksman';
_u pushBack 'rhsusf_usmc_marpat_wd_machinegunner_ass';
_u pushBack 'rhsusf_usmc_marpat_wd_jfo';
_u pushBack 'rhsusf_usmc_marpat_wd_smaw';
_u pushBack 'rhsusf_usmc_marpat_wd_explosives';
_u pushBack 'rhsusf_usmc_marpat_wd_squadleader';
_u pushBack 'rhsusf_usmc_marpat_wd_riflemanat';
_u pushBack 'rhsusf_usmc_marpat_wd_rifleman_m4';

missionNamespace setVariable [Format ["WF_%1BARRACKSUNITS", _side], _u];
if (local player) then {['BARRACKS', _side, _u] Call WFCL_fnc_initFaction};

_u=      ['rhsusf_m998_w_4dr'];
_u pushBack 'rhsusf_m998_w_s_2dr_halftop';
_u pushBack 'rhsusf_m998_w_s_4dr_halftop';
_u pushBack 'rhsusf_m1043_w';
_u pushBack 'rhsusf_m998_w_s_2dr_fulltop';
_u pushBack 'rhsusf_mrzr4_w';
_u pushBack 'rhsusf_m1043_w_m2';
_u pushBack 'CUP_B_M1165_GMV_USMC';
_u pushBack 'rhsusf_m1043_w_mk19';
_u pushBack 'CUP_B_M1151_Deploy_USMC';
_u pushBack 'rhsusf_m1045_w';
_u pushBack 'rhsusf_m1240a1_m2_usarmy_wd';
_u pushBack 'rhsusf_m1240a1_mk19_usarmy_wd';
_u pushBack 'rhsusf_m1240a1_m2crows_usarmy_wd';
_u pushBack 'rhsusf_m1240a1_mk19crows_usarmy_wd';
_u pushBack 'rhsusf_m1245_m2crows_socom_d';
_u pushBack 'rhsusf_m1245_mk19crows_socom_d';
_u pushBack 'rhsusf_CGRCAT1A2_M2_usmc_wd';
_u pushBack 'rhsusf_CGRCAT1A2_Mk19_usmc_wd';
_u pushBack 'rhsusf_M1083A1P2_WD_fmtv_usarmy';
_u pushBack 'rhsusf_M1083A1P2_B_M2_WD_fmtv_usarmy';
_u pushBack 'rhsusf_M1220_M153_M2_usarmy_wd';
_u pushBack 'rhsusf_M1220_M153_MK19_usarmy_wd';
_u pushBack 'rhsusf_M1230_M2_usarmy_wd';
_u pushBack 'rhsusf_M1230_MK19_usarmy_wd';
_u pushBack 'rhsusf_M1239_M2_Deploy_socom_d';
_u pushBack 'rhsusf_M1239_MK19_Deploy_socom_d';
_u pushBack 'rhsusf_M1117_W';
_u pushBack 'rhsusf_stryker_m1126_m2_wd';
_u pushBack 'CUP_B_LAV25_USMC';
_u pushBack 'CUP_B_LAV25M240_USMC';
_u pushBack 'CUP_B_HMMWV_Ambulance_USMC';
_u pushBack 'CUP_B_HMMWV_Avenger_USMC';
_u pushBack 'rhsusf_M978A4_BKIT_usarmy_wd';
_u pushBack 'rhsusf_M977A4_REPAIR_BKIT_usarmy_wd';
_u pushBack 'rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_wd';
_u pushBack 'rhsusf_M977A4_AMMO_BKIT_usarmy_wd';
_u pushBack 'rhsusf_M977A4_usarmy_wd';
_u pushBack 'dbo_CIV_new_bike';
_u pushBack 'CUP_B_M1030_USMC';
_u pushBack 'rhsusf_M142_usarmy_WD';
_u pushBack 'B_G_Boat_Transport_01_F';


missionNamespace setVariable [Format ["WF_%1LIGHTUNITS", _side], _u];
if (local player) then {['LIGHT', _side, _u] Call WFCL_fnc_initFaction};

_u=      ['rhsusf_m109_usarmy'];
_u pushBack 'rhsusf_m113_usarmy_M240';
_u pushBack 'rhsusf_m113_usarmy';
_u pushBack 'rhsusf_m113_usarmy_MK19';
_u pushBack 'RHS_M2A2_wd';
_u pushBack 'RHS_M2A2_BUSKI_wd';
_u pushBack 'RHS_M2A3_wd';
_u pushBack 'RHS_M2A3_BUSKI_wd';
_u pushBack 'RHS_M2A3_BUSKIII_wd';
_u pushBack 'RHS_M6_wd';
_u pushBack 'rhsusf_m1a1aimwd_usarmy';
_u pushBack 'rhsusf_m1a1aim_tuski_wd';
_u pushBack 'rhsusf_m1a2sep1wd_usarmy';
_u pushBack 'rhsusf_m1a2sep1tuskiwd_usarmy';
_u pushBack 'rhsusf_m1a2sep1tuskiiwd_usarmy';
_u pushBack 'rhsusf_m1a1fep_wd';
_u pushBack 'CUP_B_M163_USA';
_u pushBack 'CUP_B_M270_HE_USMC';

missionNamespace setVariable [Format ["WF_%1HEAVYUNITS", _side], _u];
if (local player) then {['HEAVY', _side, _u] Call WFCL_fnc_initFaction};

_u=      ['RHS_CH_47F'];
_u pushBack 'RHS_UH60M_d';
_u pushBack 'RHS_UH60M_MEV';
_u pushBack 'rhsusf_CH53E_USMC_GAU21';
_u pushBack 'RHS_UH1Y_UNARMED';
_u pushBack 'CUP_B_MH60L_DAP_2x_USN';
_u pushBack 'CUP_B_MH60L_DAP_4x_USN';
_u pushBack 'CUP_B_MH60L_DAP_2x_US';
_u pushBack 'CUP_B_MH60L_DAP_4x_US';
_u pushBack 'RHS_AH64D';
_u pushBack 'CUP_B_AH1Z_Dynamic_USMC';
_u pushBack 'RHS_UH1Y_FFAR';
_u pushBack 'RHS_UH1Y';
_u pushBack 'RHS_UH1Y_GS';
_u pushBack 'rhs_melb_mh6m';
_u pushBack 'rhs_melb_ah6m';
_u pushBack 'CUP_B_L39_CZ';
_u pushBack 'rhs_l159_CDF';
_u pushBack 'CUP_B_A10_DYN_USA';
_u pushBack 'JS_JC_FA18E';
_u pushBack 'CUP_B_GR9_DYN_GB';
_u pushBack 'JS_JC_FA18F';
_u pushBack 'RHS_C130J';
_u pushBack 'rhsusf_f22';
_u pushBack 'CUP_B_MV22_USMC';
_u pushBack 'CUP_B_C47_USA';

missionNamespace setVariable [Format ["WF_%1AIRCRAFTUNITS", _side], _u];
if (local player) then {['AIRCRAFT', _side, _u] Call WFCL_fnc_initFaction};

_u = [];

_u pushBack 'CUP_B_L39_CZ';
_u pushBack 'rhs_l159_CDF';
_u pushBack 'CUP_B_A10_DYN_USA';
_u pushBack 'JS_JC_FA18E';
_u pushBack 'CUP_B_GR9_DYN_GB';
_u pushBack 'JS_JC_FA18F';
_u pushBack 'RHS_C130J';
_u pushBack 'rhsusf_f22';
_u pushBack 'CUP_B_MV22_USMC';
_u pushBack 'CUP_B_C47_USA';

missionNamespace setVariable [Format ["WF_%1AIRPORTUNITS", _side], _u];
if (local player) then {['AIRPORT', _side, _u] Call WFCL_fnc_initFaction};

_u 			= ["C_Quadbike_01_F"];
_u pushBack "dbo_CIV_ol_bike";
_u pushBack "CUP_C_TT650_TK_CIV";
_u pushBack "CUP_C_Octavia_CIV";
_u pushBack "CUP_C_Golf4_yellow_Civ";
_u pushBack "CUP_C_Golf4_black_Civ";
_u pushBack "CUP_C_SUV_Civ";
_u pushBack "B_G_Boat_Transport_01_F";
_u pushBack "CUP_C_Ural_Civ_01";
_u pushBack "CUP_C_Ural_Civ_02";
_u pushBack "CUP_C_Ural_Open_Civ_01";
_u pushBack "C_Truck_02_fuel_F";
if ((missionNamespace getVariable "WF_C_UNITS_TOWN_PURCHASE") > 0) then {
	_u pushBack (missionNamespace getVariable "WF_WESTSOLDIER");
	_u pushBack 'rhsusf_army_ocp_arb_medic';
	_u pushBack 'rhsusf_army_ocp_arb_engineer';
	_u pushBack 'rhsusf_army_ocp_arb_riflemanat';
	_u pushBack 'rhsusf_army_ocp_machinegunner';
	_u pushBack 'rhsusf_army_ocp_aa';
};

missionNamespace setVariable [Format ["WF_%1DEPOTUNITS", _side], _u];
if (local player) then {['DEPOT', _side, _u] Call WFCL_fnc_initFaction};