Private ['_side','_tiMode','_u'];

_side = _this;

_u=      ['FGN_RuOMON_RPGGrenadier_P_KamyshB'];
_u pushBack 'FGN_RuOMON_MGunner_KamyshB';
_u pushBack 'FGN_RuOMON_Sergeant_KamyshB';
_u pushBack 'FGN_RuOMON_MarksmanVSS_KamyshB';
_u pushBack 'FGN_RuOMON_MarksmanSVD_KamyshB';
_u pushBack 'FGN_RuOMON_RiflemanAKMS_KamyshB';
_u pushBack 'FGN_RuOMON_RiflemanAK74M_KamyshB';
_u pushBack 'FGN_RuOMON_RiflemanGP25_P_KamyshB';
_u pushBack 'FGN_RuOMON_RiflemanGP25_KamyshB';
_u pushBack 'FGN_RuOMON_RiflemanAT_KamyshB';
_u pushBack 'FGN_RuOMON_RiflemanAP_KamyshB';
_u pushBack 'FGN_RuOMON_Officer_KamyshB';
_u pushBack 'FGN_RuOMON_JSergeant_KamyshB';
_u pushBack 'FGN_RuOMON_Medic_KamyshB';
_u pushBack 'FGN_RuOMON_Medic_P_KamyshB';
_u pushBack 'FGN_RuOMON_Efreitor_KamyshB';
_u pushBack 'FGN_RuOMON_RPGGrenadier_KamyshB';
_u pushBack 'FGN_RuOMON_JSergeant_P_KamyshB';
_u pushBack 'FGN_RuOMON_Sapper_P_KamyshB';
_u pushBack 'FGN_RuOMON_MGunner_P_KamyshB';
_u pushBack 'FGN_RuOMON_Sergeant_P_KamyshB';
_u pushBack 'FGN_RuOMON_MarksmanVSS_P_KamyshB';
_u pushBack 'FGN_RuOMON_MarksmanSVD_P_KamyshB';
_u pushBack 'FGN_RuOMON_RiflemanAKMS_P_KamyshB';
_u pushBack 'FGN_RuOMON_RiflemanAT_P_KamyshB';
_u pushBack 'FGN_RuOMON_Officer_P_KamyshB';

_u pushBack 'FGN_RuOBrON_Winter_RPGGrenadier';
_u pushBack 'FGN_RuOBrON_Winter_RiflemanAT';
_u pushBack 'FGN_RuOBrON_Winter_RiflemanGP25';
_u pushBack 'FGN_RuOBrON_Winter_Rifleman';
_u pushBack 'FGN_RuOBrON_Winter_Marksman';
_u pushBack 'FGN_RuOBrON_Winter_Engineer';
_u pushBack 'FGN_RuOBrON_Winter_CrewC';
_u pushBack 'FGN_RuOBrON_Winter_Medic';
_u pushBack 'FGN_RuOBrON_Winter_Efreitor';
_u pushBack 'FGN_RuOBrON_Winter_OfficerA';
_u pushBack 'FGN_RuOBrON_Winter_RiflemanAA';
_u pushBack 'FGN_RuOBrON_Winter_MGunner';

_u pushBack 'FGN_RuVityaz_RPGGrenadier_P_SMK_Winter';
_u pushBack 'FGN_RuVityaz_Officer_SMK_Winter';
_u pushBack 'FGN_RuVityaz_Sapper_P_SMK_Winter';
_u pushBack 'FGN_RuVityaz_Medic_SMK_Winter';
_u pushBack 'FGN_RuVityaz_RiflemanAT_P_SMK_Winter';
_u pushBack 'FGN_RuVityaz_MGunner_P_SMK_Winter';
_u pushBack 'FGN_RuVityaz_Sergeant_P_SMK_Winter';
_u pushBack 'FGN_RuVityaz_MarksmanVSS_P_SMK_Winter';
_u pushBack 'FGN_RuVityaz_MarksmanVSS_SMK_Winter';
_u pushBack 'FGN_RuVityaz_MarksmanSVD_P_SMK_Winter';
_u pushBack 'FGN_RuVityaz_MarksmanSVD_SMK_Winter';
_u pushBack 'FGN_RuVityaz_RiflemanAKMS_SMK_Winter';
_u pushBack 'FGN_RuVityaz_RiflemanAK74M_SMK_Winter';
_u pushBack 'FGN_RuVityaz_RPGGrenadier_SMK_Winter';
_u pushBack 'FGN_RuVityaz_Efreitor_SMK_Winter';
_u pushBack 'FGN_RuVityaz_JSergeant_SMK_Winter';
_u pushBack 'FGN_RuVityaz_RiflemanAT_SMK_Winter';
_u pushBack 'FGN_RuVityaz_RiflemanAP_SMK_Winter';
_u pushBack 'FGN_RuVityaz_MGunner_SMK_Winter';
_u pushBack 'FGN_RuVityaz_RiflemanGP25_P_SMK_Winter';
_u pushBack 'FGN_RuVityaz_RiflemanGP25_SMK_Winter';

_u pushBack 'rhs_pilot_tan';
_u pushBack 'rhs_pilot_transport_heli';
_u pushBack 'rhs_pilot_combat_heli';

missionNamespace setVariable [Format ["WF_%1BARRACKSUNITS", _side], _u];
if (local player) then {['BARRACKS', _side, _u] Call WFCL_fnc_initFaction};

_u =      ['rhs_btr60_msv'];
_u  pushBack 'rhs_btr70_msv';
_u  pushBack 'rhs_btr80_msv';
_u  pushBack 'rhs_btr80a_msv';
_u  pushBack 'rhs_tigr_msv';
_u  pushBack 'rhs_tigr_3camo_msv';
_u  pushBack 'rhs_tigr_sts_msv';
_u  pushBack 'rhs_tigr_sts_3camo_msv';
_u  pushBack 'rhs_tigr_m_msv';
_u  pushBack 'rhs_tigr_m_3camo_msv';
_u  pushBack 'CUP_O_UAZ_METIS_RU';
_u  pushBack 'CUP_O_UAZ_AA_TKA';
_u  pushBack 'CUP_O_UAZ_MG_TKA';
_u  pushBack 'CUP_O_UAZ_AGS30_TKA';
_u  pushBack 'RHS_UAZ_MSV_01';
_u  pushBack 'rhs_uaz_open_MSV_01';
_u  pushBack 'rhsgref_BRDM2_msv';
_u  pushBack 'rhsgref_BRDM2_ATGM_msv';
//_u  pushBack 'RHS_BM21_MSV_01';
_u  pushBack 'CUP_O_BM21_RU';
_u  pushBack 'CUP_O_LR_Ambulance_TKA';
_u  pushBack 'CUP_O_GAZ_Vodnik_PK_RU';
_u  pushBack 'CUP_O_GAZ_Vodnik_AGS_RU';
_u  pushBack 'CUP_O_GAZ_Vodnik_BPPU_RU';
_u  pushBack 'CUP_O_BTR90_RU';
_u  pushBack 'rhs_gaz66_msv';
_u  pushBack 'rhs_gaz66_ammo_msv';
_u  pushBack 'rhs_gaz66_flat_msv';
_u  pushBack 'rhs_gaz66o_msv';
_u  pushBack 'rhs_gaz66o_flat_msv';
_u  pushBack 'rhs_gaz66_zu23_msv';
_u  pushBack 'rhs_gaz66_repair_msv';
_u  pushBack  'rhs_zil131_vdv';
_u  pushBack 'rhs_kamaz5350_msv';
_u  pushBack 'rhs_kamaz5350_flatbed_cover_msv';
_u  pushBack 'rhs_kamaz5350_open_msv';
_u  pushBack 'rhs_kamaz5350_flatbed_msv';
_u  pushBack 'RHS_Ural_MSV_01';
_u  pushBack 'RHS_Ural_Fuel_MSV_01';
_u  pushBack 'RHS_Ural_Open_MSV_01';
_u  pushBack 'RHS_Ural_Repair_MSV_01';
_u  pushBack 'RHS_Ural_Zu23_MSV_01';
_u  pushBack 'rhsgref_cdf_reg_uaz_ags';
_u  pushBack 'rhsgref_cdf_reg_uaz_dshkm';
_u  pushBack 'rhsgref_cdf_reg_uaz_spg9';
_u  pushBack 'rhs_typhoon_vdv';
_u  pushBack 'CUP_C_TT650_RU';
_u  pushBack 'dbo_CIV_new_bike_OPFOR';

missionNamespace setVariable [Format ["WF_%1LIGHTUNITS", _side], _u];
if (local player) then {['LIGHT', _side, _u] Call WFCL_fnc_initFaction};

_u =      ['rhs_bmp2_vdv'];
_u  pushBack 'rhs_bmp2d_msv';
_u  pushBack 'rhs_bmp2_vdv';
_u  pushBack 'rhs_bmp3m_msv';
_u  pushBack 'rhs_bmp3mera_msv';
_u  pushBack 'rhs_t72bd_tv';
_u  pushBack  'rhs_t72be_tv';
_u  pushBack 'rhs_t80a';
_u  pushBack 'rhs_t80ue1';
_u  pushBack  'rhs_t90a_tv';
_u  pushBack  'rhs_t90sab_tv';
_u  pushBack  'rhs_t90sm_tv';
_u  pushBack 'rhs_sprut_vdv';
_u  pushBack 'rhs_bmd1pk';
_u  pushBack 'rhs_bmd2k';
_u  pushBack 'rhs_bmd2m';
_u  pushBack 'rhs_bmd4ma_vdv';
_u  pushBack 'rhs_zsu234_aa';
_u  pushBack 'rhs_2s3_tv';
//_u  pushBack 'rhs_2s1_tv';
_u pushBack 'CUP_O_2S6M_RU';
_u pushBack 'I_Truck_02_MRL_F_OPFOR';

missionNamespace setVariable [Format ["WF_%1HEAVYUNITS", _side], _u];
if (local player) then {['HEAVY', _side, _u] Call WFCL_fnc_initFaction};

_u =      ['RHS_Mi8AMT_vdv'];
_u  pushBack 'rhsgref_mi24g_CAS_OPFOR';
_u  pushBack 'RHS_Mi8MTV3_heavy_vdv';
_u  pushBack 'RHS_Mi8MTV3_vdv';
_u  pushBack 'CUP_O_MI6T_RU';
_u  pushBack 'CUP_O_Mi17_TK';
_u  pushBack 'CUP_O_Mi8_medevac_RU';
_u  pushBack 'RHS_Ka52_vvsc';
_u  pushBack 'rhs_ka60_c';
_u  pushBack  'CUP_O_KA60_GREY_RU';
_u  pushBack 'rhs_mi28n_vvsc';
//_u  pushBack 'RHS_TU95MS_vvs_old';
_u  pushBack 'CUP_O_Su25_Dyn_TKA';
_u  pushBack 'rhs_mig29sm_vmf';
_u  pushBack 'CUP_O_AN2_TK';
_u  pushBack 'CUP_O_C47_SLA';
_u pushBack 'CUP_O_L39_TK';
_u pushBack 'I_Plane_Fighter_03_dynamicLoadout_F_OPFOR';
_u pushBack 'CUP_O_SU34_RU';
_u pushBack 'JS_JC_SU35';
//_u  pushBack 'RHS_T50_vvs_generic_ext';

missionNamespace setVariable [Format ["WF_%1AIRCRAFTUNITS", _side], _u];
if (local player) then {['AIRCRAFT', _side, _u] Call WFCL_fnc_initFaction};

_u = [];

_u  pushBack 'CUP_O_Su25_Dyn_TKA';
_u  pushBack 'rhs_mig29sm_vmf';
_u  pushBack 'CUP_O_AN2_TK';
_u  pushBack 'CUP_O_C47_SLA';
_u pushBack 'CUP_O_L39_TK';
_u pushBack 'I_Plane_Fighter_03_dynamicLoadout_F_OPFOR';
_u pushBack 'CUP_O_SU34_RU';
_u pushBack 'JS_JC_SU35';
//_u  pushBack 'RHS_T50_vvs_generic_ext';

missionNamespace setVariable [Format ["WF_%1AIRPORTUNITS", _side], _u];
if (local player) then {['AIRPORT', _side, _u] Call WFCL_fnc_initFaction};

_u 			= ["C_Quadbike_01_F_OPFOR"];
_u pushBack "dbo_CIV_ol_bike_OPFOR";
_u pushBack "CUP_C_TT650_TK_CIV_OPFOR";
_u pushBack "CUP_C_Octavia_CIV_OPFOR";
_u pushBack "CUP_C_Golf4_yellow_Civ_OPFOR";
_u pushBack "CUP_C_Golf4_black_Civ_OPFOR";
_u pushBack "CUP_C_SUV_TK_OPFOR";
_u pushBack "CUP_O_PBX_RU_OPFOR";
_u pushBack "CUP_C_Ural_Civ_01_OPFOR";
_u pushBack "CUP_C_Ural_Civ_02_OPFOR";
_u pushBack "CUP_C_Ural_Open_Civ_01_OPFOR";
_u pushBack "C_Truck_02_fuel_F_OPFOR";
if ((missionNamespace getVariable "WF_C_UNITS_TOWN_PURCHASE") > 0) then {
	_u pushBack (missionNamespace getVariable "WF_EASTSOLDIER");
	_u pushBack 'FGN_RuOMON_Medic_KamyshB';
	_u pushBack 'FGN_RuOMON_Sapper_P_KamyshB';
	_u pushBack 'FGN_RuOMON_RiflemanAT_P_KamyshB';
	_u pushBack 'FGN_RuOMON_MGunner_P_KamyshB';
	_u pushBack 'FGN_RuOBrON_Winter_RiflemanAA';
};

missionNamespace setVariable [Format ["WF_%1DEPOTUNITS", _side], _u];
if (local player) then {['DEPOT', _side, _u] Call WFCL_fnc_initFaction};
